[workspace]
members = ["crates/rmcp", "crates/rmcp-macros", "examples/*"]
default-members = ["crates/rmcp", "crates/rmcp-macros"]
resolver = "2"

[workspace.dependencies]
rmcp = { version = "0.16.0", path = "./crates/rmcp" }
rmcp-macros = { version = "0.16.0", path = "./crates/rmcp-macros" }

[workspace.package]
edition = "2024"
authors = ["4t145 <u4t145@163.com>", "ra0x3 <ractz@pm.me>"]
version = "0.16.0"
license = "Apache-2.0"
license-file = "LICENSE"
repository = "https://github.com/modelcontextprotocol/rust-sdk/"
description = "Rust SDK for Model Context Protocol"
keywords = ["mcp", "sdk", "tokio", "modelcontextprotocol"]
homepage = "https://github.com/modelcontextprotocol/rust-sdk"
categories = [
    "network-programming",
    "asynchronous",
]
readme = "README.md"
